---
abstract: 'A validation module for validating Results based on their column structure'
author:
  - 'Sean Zellmer <sean@lejeunerenard.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Validation-DBStruct
requires:
  DBIx::Class: 0
resources:
  bugtracker: https://github.com/lejeunerenard/DBIx-Class-Validation-DBStruct/issues
  homepage: https://github.com/lejeunerenard/DBIx-Class-Validation-DBStruct
  repository: https://github.com/lejeunerenard/DBIx-Class-Validation-DBStruct.git
version: 0.2
